django_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name="accounts"

urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login"
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

django_website/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('django_website.apps.public.urls')),
    path("accounts", include('django_website.apps.accounts.urls')),
]
 

django_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    
    def __str__(self):
        return self.name

class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

django_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

django_website/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock%}

{% block content %}
<h1>
    About
</h1>


{% endblock %}

django_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} About {% endblock%}

{% block content %}
<h2>Login</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>

</form>


{% endblock %}

django_website/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock%}

{% block content %}
<h1>
    {{ user.get_full_name }} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{ profile.bio|default:""}}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{ website }}">{{ website }}</a>
            {% endwith %}
        </div>
        <br/>
        
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>
                    {{ interest.name }}{% if not forloop.last %}, {% endif %}
                </span>
            {% endfor %}

        </div>
    {% endif %}
{% endwith %}


{% endblock %}

django_website/templates/base.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} forumlike {% endblock%}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static '/theme/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static '/css/main.css' %}" rel="stylesheet" />

</head>
<body>

    {% include 'navbar.html' %}
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static '/theme/js/scripts.js' %}"></script>
</body>
</html>

django_website/templates/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock%}

{% block content %}
<h1>
    Contact
</h1>


{% endblock %}

django_website/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Home {% endblock%}

{% block content %}

<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'img/logo.png' %}" alt="" />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">You Can Do ANYTHING</h1>
    </div>
</header>
<h1>
    Homepage
</h1>


{% endblock %}

django_website/templates/navbar.html
{% url 'public:index' as index_url%}
{% url 'public:about' as about_url %}
{% url 'public:contact' as contact_url %}

<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{ index_url }}">Django Website</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>

                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>

                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger {% if request.path == contact_url %}active{% endif %}" href="{% url 'public:contact' %}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>



<!-- <nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %} <a href="{{ index_url }}">Home</a>{% endif %}</span>

    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %} <a href="{{ about_url }}">About</a>{% endif %}</span>

    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{% url 'public:contact' %}">Contact</a>{% endif %}</span>

    <span style="float: right;">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            <span> Hi {% if request.path == profile_url %}{{ user.username }}{% else %}<a href="{{ profile_url }}">{{user.username}}</a>{% endif %}</span>
            <span> <a href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
            <span> <a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}

    </span>
</nav> -->